# Generated by Django 2.0.3 on 2018-07-08 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Index')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
